name: Cypress Smoke Test

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  cypress-smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Start Next.js app
        run: yarn dev &
        env:
          NODE_ENV: test
        continue-on-error: false

      - name: Wait for app to be ready
        run: npx wait-on http://localhost:3000

      - name: Run Cypress smoke tests
        run: yarn test:smoke

      - name: Upload Cypress HTML report
        uses: actions/upload-artifact@v4
        with:
          name: cypress-report
          path: cypress/reports/mochawesome/*.html
          retention-days: 1
